/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xwh_ndktest_JNITest */

#ifndef _Included_com_xwh_ndktest_JNITest
#define _Included_com_xwh_ndktest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xwh_ndktest_JNITest
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xwh_ndktest_JNITest_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
